language: python

install:
  - curl -fLo /tmp/pandoc.deb https://github.com/jgm/pandoc/releases/download/2.9.1.1/pandoc-2.9.1.1-1-amd64.deb
  - sudo dpkg -i /tmp/pandoc.deb
  - sudo apt-get install -f
  - rm /tmp/pandoc.deb
  - git clone "https://github.com/entangled/filters.git" /tmp/filters
  - pip install /tmp/filters

script:
  - make regex.html
  - mv regex.html index.html
  - make regex.pl

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
